spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotel_reservation_system
    username: root
    password: 12345

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#  security:
#    user:
#      name: root
#      password: 12345